import ProjectsNavbar from "@/components/ProjectsNavbar";
import ActiveSectionContextProvider from "@/context/ActiveProvider";
import Provider from "@/context/Provider";
import { Poppins } from "next/font/google";
import "../globals.css";
import Contact from "@/components/Contact";
const poppins = Poppins({ subsets: ["latin"], weight: ["500", "800", "400"] });
export const metadata = {
  title: "Almahdi's Projects",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} max-w-5xl bg-slate-200 dark:bg-[#212121] text-[#212121] dark:text-slate-200 mx-auto transition-all duration-500`}
      >
        <ActiveSectionContextProvider>
          <Provider>
            <ProjectsNavbar />
            {children}
            <Contact />
          </Provider>
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
